### ISSUE TITLE
Binding multiple keys with the bind dictionary doesn't work?

### ISSUE THREAD

**Issue by ghost** [ccampbell/mousetrap#122]
Does the bind dictionary (*) also support binding multiple keys like the documentation? It doesn't seem to work, but I can't find the problem.

<pre>Mousetrap.bind({
"['l', 'm']": function() {console.log('l, m')}
});</pre>

(*) https://gist.github.com/ccampbell/3154320

**Comment by rayshan** [comment]
Maybe we can reopen this now that we can use any object as keys in ES6?
