### ISSUE TITLE
Prevent repeat events from holding a key

### ISSUE THREAD

**Issue by bblack** [ccampbell/mousetrap#128]
Feature request:

If I bind a callback to, say, the A key, and then I hold down the A key, the callback will be called many times, rapidly, until I release the A key.

It would be nice to have an option to have such a callback only fire once.

**Comment by jomido** [comment]
Here's one way:

    Mousetrap.bindOnce = (function (keys, fn, kind) {

        var keyState = {}, wrap;

        return function (keys, fn, kind) {

            wrap = fn;

            if (kind === 'keydown') {

                wrap = function (e) {

                    if (keyState[keys] !== 'down') {

                        keyState[keys] = 'down';
                        fn(e);
                    }
                };

                Mousetrap.bind(keys, function (e) {
                    keyState[keys] = 'up';
                }, 'keyup');
            }

            return Mousetrap.bind(keys, wrap, kind);

        };

    }());

Then you can just do:

    Mousetrap.bindOnce('r', function(e) {

        // do something

    }, 'keydown');

**Comment by dpren** [comment]
`keyboardEvent` has a `.repeat` boolean property indicating if an event is a repeat.

It's not currently supported in Safari, but in the event that they add support, a very simple solution would be adding `if (e.repeat) return;` inside `_handleKeyEvent`. Maybe toggle it with a mixin of some sort.

**Comment by jessicard** [comment]
+1

**Comment by kafeltz** [comment]
These nice features could be done with special binding syntax instead doing bindWithSuffixes.

Mousetrap.bind('a', function());
Mousetrap.bind('a+', function()); // ow yeah, regex-like

Looks pretty.

**Comment by cbou** [comment]
+1

**Comment by bblack** [comment]
Closing this, since as @dpren points out, `KeyboardEvent.repeat` can be used for this purpose. It is in the [latest UI Events working draft](https://w3c.github.io/uievents/#dom-keyboardevent-repeat), and has been since [at least 2015](https://www.w3.org/TR/2015/WD-uievents-20151215/#widl-KeyboardEventInit-repeat). It's suported in the latest Chrome and Firefox, and Safari since the 10.1 release last month.
