### ISSUE TITLE
delete key

### ISSUE THREAD

**Issue by jedierikb** [ccampbell/mousetrap#129]
Noticed that the 'delete' key does not appear to be available in mousetrap.

For me, 'del' captures the keypad 'delete' key not the main keyboard 'delete' key.

How would one capture the 'standard' delete key?  Much thanks.

**Comment by christiangenco** [comment]
For people landing here from google, here's a safe way to capture both the `backspace` and `delete` keys:

    Mousetrap.bind(["del", "backspace"], myFunction);
