### ISSUE TITLE
Keybinding on specific input?

### ISSUE THREAD

**Issue by desduvauchelle** [ccampbell/mousetrap#196]
Hello,
Great plugin, thanks! 

Any chance we can bind it to a specific input? ie, I want to create a shortcut to submit a post (cmd+enter) from a textarea. Is that possible now?

**Comment by ready4god2513** [comment]
@desduvauchelle Did you ever find the answer to this?  I would like to do the same.

**Comment by desduvauchelle** [comment]
Not with mousetrap. I ended up coding it manually with event.keyCode...

**Comment by wired00** [comment]
Could you simply check for the global event then process only if the focus is currently on the particular input?

**Comment by vanceza** [comment]
Mousetrap(domElement) creates an instance of mousetrap which listens to only one element, this is documented.

**Comment by ccampbell** [comment]
@vanceza thanks. This was not possible at the time this ticket was created.
