### ISSUE TITLE
International keyboard layouts do not work correctly

### ISSUE THREAD

**Issue by frontsideair** [ccampbell/mousetrap#2]
I tried the examples on demo page using standard Turkish (Q) layout, but some of them didn't work. (Namely, '$' and '*'.)

Now I tried them again and somehow made them work. $ character is typed using AltGr+4 combination, but it didn't work with it or the US variant Shift+4; however it works for AltGr+Shift+4.

On the other hand, asterisk character has a seperate key for itself on Turkish layout. But it also doesn't work. It works by combining Turkish and US layouts and pressing AltGr+Shift+8 --and followed by 'a', of course, for the example to work.

**Comment by skfd** [comment]
tHenlo, are
