### ISSUE TITLE
Error in the documentation

### ISSUE THREAD

**Issue by iirelu** [ccampbell/mousetrap#210]
![blender](https://cloud.githubusercontent.com/assets/3432543/3448724/eb904eb0-015c-11e4-8f8a-f864736909ed.png)

The last code example is wrong and misleading. It should either be an anonymous function, like the previous examples, or:

```js
Mousetrap.bind('mod+s', _saveDraft);
```

**Comment by ccampbell** [comment]
Apparently soon means almost a year :disappointed: 

Updated now
