### ISSUE TITLE
FireFox shortcuts clash with Mousetrap shortcuts

### ISSUE THREAD

**Issue by solveigo** [ccampbell/mousetrap#211]
Hey. I'm using a single letter shortcut for something, the letter "D".

This works fine in Chrome and IE 

In Firefox it behaves very badly. It also fires off when I use the "Alt-D" browser shortcut (to go up to the navigation bar). Pressing Alt-D in the other browsers is fine.

**Comment by kleinfreund** [comment]
Unfortunately, this has to be re-opened as #452 reverted the pull request that intended to fix this issue.
