### ISSUE TITLE
Need to know which object was selected or has focus when we trigger shortcut key

### ISSUE THREAD

**Issue by rahuljain257** [ccampbell/mousetrap#238]
Hi Admin,

Is there any way which I can know what control type was selected @ the time of triggering the shortcut. The reason for asking this question is I want to perform some logic and that logic need to know which control was selected in the grid.

So please let me know in your library any predefined methods do the job for the same or you can let me know some workaround.

**Comment by Boldewyn** [comment]
That looks like `event.target` is what you're after:

    Mousetrap.bind('f', function(evt) {
      console.log(evt.target);
    });

Or did I get the requirement wrong?

**Comment by ccampbell** [comment]
The key event will have the target on it as @Boldewyn mentioned.  That will map back to the element if it is an element that can receive keyboard events.  

If you have specific elements in your UI then you have to keep track of that outside of mousetrap.

See this page for an example of getting the focused element http://stackoverflow.com/questions/11277989/how-to-get-the-focused-element-with-jquery
