### ISSUE TITLE
Why is 'keydown'/'keyup' not triggering on the first key press?

### ISSUE THREAD

**Issue by MrDoubleJump** [ccampbell/mousetrap#240]
I have a sprite that animates on the x-axis via the left and right arrow keys.  It is setup to move on 'keydown' and stop on 'keyup'. The problem is, it only animates after the second key press.  I've also tried holding down either left or right keys - which upon 'keyup the sprite still animates.  Again, this cancels out after the second press of the 'same' key.

JSFiddle: http://jsfiddle.net/MrDoubleJump/scuz8s4h/75/

My events start at line 54. 

I've set up a console log, so it may be easier to get an understanding by opening up the console while taking a look at the events.
Oh yeah, I'm using the EaselJS library, not sure that makes a different but any-hoo, any help on this would be awesome.

Thanks smart people!

**Comment by ccampbell** [comment]
Hi @MrDoubleJump,

I updated your jsfiddle and this seems to work:
http://jsfiddle.net/scuz8s4h/79/

The problem is that you are not binding the mousetrap listeners until after you get a window.onkeyup or window.onkeydown event so that is why it is not working the first time.  You don't need to bind your own listeners cause mousetrap already does that.

**Comment by MrDoubleJump** [comment]
Brilliant!  That makes perfect sense now that I see the fix, thanks!

**Comment by ccampbell** [comment]
No problem!

**Comment by jeudaya** [comment]
Hi ccampbell,

your fiddle link is not working, can you please provide some snippet again?

**Comment by ccampbell** [comment]
Unfortunately I do not remember what it was. The original fiddle is also a 404. JS fiddle must have deleted them. If you have your own fiddle that you are having trouble with feel free to share it, and I can take a look
