### ISSUE TITLE
Executing function when focusing on input form

### ISSUE THREAD

**Issue by t0n1zz** [ccampbell/mousetrap#242]
So i notice this when i trying to input form, i just can't do the keyboard shortcut to execute my submit button when i still focus/edit/typing in any of input form (text,select)

but if i'm not focusing on any input form then it works...

here is my code

        Mousetrap.bind(['alt+t'], function() {
            document.getElementById("tambah").click();
        });
        Mousetrap.bind(['alt+s'], function() {
            document.getElementById("simpan").click();
        });
        Mousetrap.bind(['alt+m'], function() {
            document.getElementById("simpan2").click();
        });
        Mousetrap.bind(['alt+b'], function() {
            document.getElementById("batal").click();
        });

**Comment by Nilpo** [comment]
If a form element is focused, the browser is capturing keypresses because that is the native behavior.  (Try pressing the Enter key.  Pressing the Enter key while focusing on a form element will execute the default form action.)

**Comment by DelvarWorld** [comment]
Is there a better suggested solution for this? Keyboard shorcuts like save (ctrl+s) aren't very useful if they stop working in random places in a web app.

**Comment by ccampbell** [comment]
As of right now you can either 

- Add the `mousetrap` class to the input element(s) you want to receive keyboard shortcuts on

OR

- Use the [global bind](https://github.com/ccampbell/mousetrap/tree/master/plugins/global-bind) plugin to make certain keyboard shortcuts available globally

In the future

I am planning to add support for binding mousetrap events to specific elements (See #154).  I will see if I can get it out this weekend.  I know I've been really slacking on this project lately.  If you use that approach you could, for example, bind `ctrl+s` to the form itself and then any inputs inside of it will fire the event without it being stopped.

I also think it was a poor decision on my part to stop all events from triggering when inside form fields by default.  I plan on changing this behavior down the road so if you use the `meta` (command) or `ctrl` modifiers your shortcuts will fire even inside of form inputs.  It was kind of an oversight cause regular keys, shift+key, and option+key events should not fire by default.

**Comment by ccampbell** [comment]
Now that you can bind shortcuts to forms and form fields directly I'm going to close this out.  See http://craig.is/killing/mice#wrapping for more information.

One note, about the original issue.  I would not recommend binding to the alt/option key in a text input because that is actually how you type special characters.
