### ISSUE TITLE
Stop events occuring in input fields when using a shadow DOM

### ISSUE THREAD

**Issue by robinsk** [ccampbell/mousetrap#245]
I'm using Mousetrap with Polymer, and I just noticed that events in inputs aren't stopped by default. The reason for this is that Mousetrap uses `target` or `srcElement` in the `stopCallback` function, but when the event occurs in a shadow DOM, the events are retargeted to look like they come from the host element.

A fix would be to use the first element from the event path if `event.path` is available.

**Comment by ccampbell** [comment]
I'd be happy to fix this...  Do you have an example or test that I could use?
