### ISSUE TITLE
bower support please

### ISSUE THREAD

**Issue by thecotne** [ccampbell/mousetrap#248]

**Comment by miguelmota** [comment]
I agree that it needs a bower.json and there's plenty of pull requests that mention this https://github.com/ccampbell/mousetrap/pulls
but the author looks like he has abandoned this repo since it hasn't been updated for months. You're better off forking it or looking elsewhere.

**Comment by dzhus** [comment]
+1 to the request

**Comment by nfang** [comment]
:+1:

**Comment by attenzione** [comment]
+1

**Comment by bocharsky-bw** [comment]
:+1:

**Comment by leocaseiro** [comment]
:+1:
