### ISSUE TITLE
amd broken by Mousetrap fn having parameter

### ISSUE THREAD

**Issue by herby** [ccampbell/mousetrap#255]
https://github.com/ccampbell/mousetrap/blame/master/mousetrap.js#L424 breaks amd loading. Since function now has a parameter, requirejs passes `require` function in, which `Mousetrap` function tries to use as a `targetElement`.

**Comment by ccampbell** [comment]
Hey thanks for this.  I'm not really familiar with amd.  What is the correct way to handle this?

**Comment by ccampbell** [comment]
Is it just a matter of changing it to this maybe?

```diff
     if (typeof define === 'function' && define.amd) {
-        define(Mousetrap);
+        define(function() {
+            return Mousetrap;
+        });
     }
```

**Comment by herby** [comment]
Craig Campbell wrote:
> Is it just a matter of changing it to this maybe?
>
>       if (typeof define === 'function'&&  define.amd) {
> -        define(Mousetrap);
> +        define(function() {
> +            return Mousetrap;
the function is called by amd loader and it should return the exported value, so probably `return Mousetrap();` if that worked for <=1.5.0 in the `define(Mousetrap)` way.

**Comment by ccampbell** [comment]
Hmm, but that means you will only get one instance of mousetrap and not be able to create new ones which 1.5 supports.  

That's why I think it should return the constructor.  I changed the way mousetrap works.

**Comment by herby** [comment]
Ah. In that case you should make it 2.0.0, not 1.5.0 :-( (semver ^1.something.something treats 1.5.0 as compatible, which it is not, after such a change).

Whatever, if that's the case, and you want to export the factory, not the instance, as you did before, than of course it should go as you said.
Whatever way you choose to fix, I can update my code to treat it is as a factory, not as a thing-that-can-be-called-bind-and-unbind as it was before 1.5.0.

Craig Campbell wrote:

**Comment by herby** [comment]
Oh. I see you added `Mousetrap.init` to overcome the breaking change... then yes, I take it back and 1.5.0 is ok (but be it me, I would do a `2.0.0` with the new functionality and did not bother with backward compat).

To recap, your `define(function() { return Mousetrap; });` is fine, hope to see it released soon.

**Comment by ccampbell** [comment]
Yeah, I didn't want to make it a breaking change cause for the common use case of just binding keys globally to the document, it is very convenient to be able to use it out of the box without having to create a new instance first :smile:

Okay cool
