### ISSUE TITLE
unbinding events when wrapping specific elements

### ISSUE THREAD

**Issue by luujam1** [ccampbell/mousetrap#256]
Hi,

Not sure if this is really an issue but I'm unable to unbind mousetrap events which were bound to specific elements (e.g. Mousetrap(el).unbind('esc')). Could it cause possible memory leaks if the DOM which the mousetrap event was bound to is removed? Also creates issues if we do the same bind to the specific element more than once as it doesn't overwrite the old one.

Another issue I've encountered is in testing these keyboard events through Mousetrap(el).trigger('esc'). It works fine when you don't provide the specific element but when you do the event doesn't seem to pick up.

**Comment by ccampbell** [comment]
@luujam1 I should have clarified this in the documentation.

Internally mousetrap creates a new instance every time you do `Mousetrap(el)`.  I'm not currently keeping track of mousetrap instances bound to specific elements if you try to do them again.

This means you have to store a mousetrap instance and use that one to unbind and trigger.  For example

```javascript
var mousetrap = new Mousetrap(el);
mousetrap.bind('esc', _handleEscape);
mousetrap.trigger('esc');
mousetrap.unbind('esc');
```

new Mousetrap(el) and Mousetrap(el) do the same thing right now.  I hope this helps

**Comment by luujam1** [comment]
Thanks for clearing that up. Great library!
