### ISSUE TITLE
Manual triggering of events doesn't provide an event object

### ISSUE THREAD

**Issue by luujam1** [ccampbell/mousetrap#257]
Currently testing some of my keyboard navigation functions. When I want to simulate a keypress I use 

   Mousetrap.trigger('down');

The binded function to the keypress is as follows:

Mousetrap.bind('down', function(e) {
   //do something
   e.stopPropagation();
});

Without an event object passed in the function will error out.

**Comment by ccampbell** [comment]
Yeah this is mentioned in the documentation, but I suppose I can make it a little more clear

https://craig.is/killing/mice#api.trigger

**Comment by luujam1** [comment]
I see, so how would I pass an event object to the mousetrap bound function then? The stopPropagation call is required due to mousetrap being bound to a specific element. I've tried triggering the key event using JQuery but mousetrap doesn't pick up on it:

                       //simulate down keypress
			var press = jQuery.Event("keypress");
			press.which = 40;
			el.trigger(press);

**Comment by ccampbell** [comment]
Hmmm, mousetrap should pick up on it.  By default it is listening on `keyup`, `keydown`, and `keypress` events bound to `document`.  I'm not sure how jquery triggers them tho.  

You may have to try `$(document).trigger(press)` instead of `el.trigger(press)`

**Comment by marchaos** [comment]
I'm having this problem too: 
The trigger function looks like:

```js
Mousetrap.prototype.trigger = function(keys, action) {
        var self = this;
        if (self._directMap[keys + ':' + action]) {
            self._directMap[keys + ':' + action]({}, keys);
        }
        return self;
    };
```

I think it should be 

```js
Mousetrap.prototype.trigger = function(keys, action, event) {
       event = (event) || {}
        var self = this;
        if (self._directMap[keys + ':' + action]) {
            self._directMap[keys + ':' + action](event, keys);
        }
        return self;
    };
```
