### ISSUE TITLE
_belongsTo error due to element being null

### ISSUE THREAD

**Issue by davidmaxwaterman** [ccampbell/mousetrap#274]
Hi,

I'm developing some features on an app, and I have them working on Chrome, but now I am testing on Firefox I am getting an error.

The issue seems to be in the _belongsTo() function which is recursive. After several iterations, it calls itself with the element parameter as null - ie element.parentNode is null.

I've not figured out what is wrong, but I am suspecting it is something to do with the webcomponents implementation of shadow-dom - or lack thereof - that is certainly one significant difference between chrome and firefox, and since thie _belongsTo() function seems to be ascending the DOM tree, then perhaps it is related.

It'd be great to get some opinion of how this problem can be worked-around.

In the meantime, I'll see if I can reduce my code into a simple test case.

Thanks,

Max.

webcomponentsjs#0.5.2
mousetrap#1.5.2
polymer#0.5.5

stack trace :
> console.trace():
<anonymous> debugger eval code:1
_belongsTo() mousetrap.js:421
_belongsTo() mousetrap.js:421
_belongsTo() mousetrap.js:421
_belongsTo() mousetrap.js:421
_belongsTo() mousetrap.js:421
_belongsTo() mousetrap.js:421
Mousetrap.prototype.stopCallback() mousetrap.js:970
_fireCallback() mousetrap.js:601
Mousetrap/self._handleKey() mousetrap.js:666
Mousetrap.prototype.handleKey() mousetrap.js:983
_handleKeyEvent() mousetrap.js:726
invoke() webcomponents.js:1070
dispatchBubbling() webcomponents.js:1024
dispatchEvent() webcomponents.js:998
dispatchOriginalEvent() webcomponents.js:953

**Comment by davidmaxwaterman** [comment]
It's a little odd...looking into it some more, it seems to ascend the DOM tree until it gets to the document, but the test :

```
        if (element === document) {
```

fails.

If I test `element`, I get :

```
Object { __impl4cf1e782hg__: HTMLDocument → app, parentNode_: undefined, firstChild_: undefined, lastChild_: undefined, nextSibling_: undefined, previousSibling_: undefined, treeScope_: Object, __observer: Object, stagingDocument_: Object, _pgListeners: 1, 2 more… }
```

and `document` is :

```
HTMLDocument → http://localhost:8282/app
```

They both seem to be 'document' in some form, but :

```
> element === document
false
```

I am concluding that shadow-dom isn't an issue in this problem.
Any ideas?

Max.

**Comment by davidmaxwaterman** [comment]
FWIW, this seems to fix the problem :

```
413        if (element.parentNode === null) {
```

Do you see any problem with making that change?

**Comment by ccampbell** [comment]
Yeah you are totally right... there needs to be a check at the top of `_belongsTo`

```javascript
if (element === null) {
    return false;
}
```

Feel free to send a pull request or I will try to get this out later tonight

**Comment by davidmaxwaterman** [comment]
I hope that PR is as you intended...I checked against document too, since that'll happen one iteration sooner, iinm.

**Comment by davidmaxwaterman** [comment]
Any hope of getting this fix in and released soon? I have a PR on my own s/w that is waiting on it, so it'd be great to get #275 merged.

**Comment by davidmaxwaterman** [comment]
FYI, we'll be switching to using my fork so we can continue to move forward (and I don't keep having to rebase my branch) - the power of open source :)

**Comment by ccampbell** [comment]
Okay. Yes, I will try to get it released within the next couple days, but good that you are not held up on it.

**Comment by devinivy** [comment]
This is affecting us too!  Would love to see #275 merged– it looks good.
