### ISSUE TITLE
Save and restore state

### ISSUE THREAD

**Issue by raphink** [ccampbell/mousetrap#277]
It would be useful to be able to save the current bindings and restore them later.

Use case:

I have an interface with bindings for 'j'/'k' (for down and up in a list). When pressing 'm', I open a menu to choose a report, and I want to remap 'j'/'k' to go up and down in that menu instead. If I espace the menu however, I need to go back to the previous mapping.

Since the menu can be triggered from various contexts, it's a bit complex to remap after the menu is closed, so it would be much more practical to save the mappings and restore them.

**Comment by ccampbell** [comment]
This is totally possible using an extension... also see my comments on #247 for some ideas of how you could implement it.  You can basically juggle around a few different mousetrap objects (perhaps coupled with the pause/unpause plugin).

You could have a `documentMousetrap` and then a `menuMousetrap`, and when the menu is focused you could pause the document one.  That is not the prettiest API, but you could wrap it with something a bit nicer.

I don't plan on implementing this natively in mousetrap though.

**Comment by raphink** [comment]
That is great. Thank you.
