### ISSUE TITLE
can't require() in nodejs land

### ISSUE THREAD

**Issue by DelvarWorld** [ccampbell/mousetrap#283]
> require('mousetrap')
    ReferenceError: window is not defined

Simply requiring shouldn't have side effects :)

See also https://github.com/ccampbell/mousetrap/issues/244

**Comment by DelvarWorld** [comment]
The best friends club:
- https://github.com/ccampbell/mousetrap/issues/283
- https://github.com/zeroclipboard/zeroclipboard/issues/568
- https://github.com/thlorenz/brace/issues/30

**Comment by ccampbell** [comment]
Fixed with #331
