### ISSUE TITLE
ctrl+plus doesn't work for the second plus key

### ISSUE THREAD

**Issue by stbaer** [ccampbell/mousetrap#291]
Hi, I bind a shortcut for zooming (and to prevent the browser zoom) like this:

Mousetrap.bind('ctrl+plus', function (e) {
        e.preventDefault();
       ...
})

It works fine with the plus key on the numpad, but not with the second plus key. Minus works with both minus keys.

I also tested it on a small laptop without numpad and it doesn't work with the plus key there.

Not sure if it's a bug or if I should use e.g. another shortcut in additon.

**Comment by anko** [comment]
By “second plus key”, do you mean the one behind <kbd>Shift</kbd>+<kbd>=</kbd>?

Try binding to `ctrl+shift+=` instead.

**Comment by alinnert** [comment]
I've discovered the same problem. But I'm using a German QWERTZ keyboard layout
(see: https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/KB_Germany.svg/2000px-KB_Germany.svg.png)
There you don't need <kbd>shift</kbd> to enter the <kbd>+</kbd> key.
I just looked up the key codes. The <kbd>+</kbd> on the numpad is `107`, the <kbd>+</kbd> next to the <kbd>return</kbd> key is `187`.

**Comment by kafeltz** [comment]
Would not be nice to solve this issue with pure jQuery ou native browser? So weird using mousetrap to solve this preventing zoom.

**Comment by stbaer** [comment]
Just to clarify, I had no trouble fixing it by additionally binding to another key (using 'ctrl+plus' and 'ctrl+=' now). If mousetrap doesn't intend to capture this case with 'ctrl plus' this issue can probably be closed. 

@kafeltz - this is not just for preventing zoom - its in my case for triggering the zoom function of a canvas app and it's just one of many kb shortcuts (pure javascript / no jquery btw).
