### ISSUE TITLE
1.5.3 download contains 1.5.2 mousetrap.js

### ISSUE THREAD

**Issue by will-moore** [ccampbell/mousetrap#294]
It seems that the source code zip download for the 1.5.3 release contains the mousetrap.js for 1.5.2, although the mousetrap.min.js is 1.5.3 as expected.

**Comment by ccampbell** [comment]
I'm pretty sure it is actually 1.5.3, but I just forgot to increase the version number in the file

**Comment by ccampbell** [comment]
Yup ab4327c82b1b2e38b1d8ac5576f32a49e4441ea3

**Comment by will-moore** [comment]
I get this (very minor diff)
```
$ diff ~/Downloads/mousetrap-1.5.2/mousetrap.js ~/Downloads/mousetrap-1.5.3/mousetrap.js
413c413
<         if (element === document) {
---
>         if (element === null || element === document) {
```

**Comment by ccampbell** [comment]
Yes.  That is all changed in version 1.5.3. See #275

I just forgot to increase the version number in mousetrap.js until after I tagged the release.  The code is the 1.5.3 code.
