### ISSUE TITLE
Play, Pause, Forward, Back

### ISSUE THREAD

**Issue by Evanion** [ccampbell/mousetrap#296]
I'm missing the keys for 'Play', 'Pause', 'Forward', 'Back', 'Stop' etc that keyboards have now days.

**Comment by kafeltz** [comment]
Is that possible?
A quick snippet show me that in my browser these keys do not trigger key event.

$(document).on("keypress", function(event) { console.log(event); });

**Comment by Evanion** [comment]
ok, than thats a pretty solid reason why it's missing ;)
