### ISSUE TITLE
Multiple bindings for the same key combo the 3rd

### ISSUE THREAD

**Issue by NicBright** [ccampbell/mousetrap#299]
Hi there,

I just wanted to push this topic once more because I'm in need for this feature as well (multiple widgets of the same type that need all to be closable when pressing `<ESC>`). Any chance of giving it a higher priority?

Previous mentions: #162 + #98 

Thanks and Regards,
Nicolas

**Comment by kafeltz** [comment]
Can't this be solved without mousetrap?

addEventListener with ESC key, close widgets. So light.

**Comment by NicBright** [comment]
Agreed. In this particular use case I can use native DOM api.
Please forgive me for having pushed this once more. However it'd still be nice if this feature could be added with Mousetrap 2.

Thanks and Regards,
Nicolas
