### ISSUE TITLE
Synthesizes key down on modifier up

### ISSUE THREAD

**Issue by andyross** [ccampbell/mousetrap#3]
On my browser (Chrome 20.0.1132.47 on Fedora 17) and a US keyboard:
1. Browse to the demo at http://craig.is/killing/mice
2. Press and hold the shift key
3. Press and hold the '4' key 
4. The "$" item correctly illuminates
5. Release the shift key.  The "4" item incorrectly illuminates.  "4" was never typed.

**Comment by ccampbell** [comment]
Closing this out since there has been no reply in a while and a number of things have changed since then
