### ISSUE TITLE
Add support for pausebreak

### ISSUE THREAD

**Issue by robincafolla** [ccampbell/mousetrap#313]
Hi there,

It would be great if we had support for the pause-break button. Probably under `pausebreak`. It's a very easy addition.

**Comment by ccampbell** [comment]
This is now possible to do yourself as of [version 1.6.0](https://github.com/ccampbell/mousetrap/releases/tag/1.6.0)

You can use [Mousetrap.addKeycodes](https://craig.is/killing/mice#api.addKeycodes).
