### ISSUE TITLE
Can't bind "shift+2"

### ISSUE THREAD

**Issue by Twisterking** [ccampbell/mousetrap#321]
Hi there.
So I have several tabs in my webapp and would like to jump between them with `shift + numbers keys`.
`shift+1` would switch to tab 1, `shift+2` to tab 2 and so on ...

But for whatever reason `shift+2` does **not work**.
All the other numbers work -  `shift+1`,  `shift+3`, ...
Dafuq? Any ideas on this?
I am on a mac with a german layout apple keyboard.

Can someone help?!

**Comment by kafeltz** [comment]
Does it happens in any browser? Could be OS specific issue?

**Comment by robincafolla** [comment]
What letter or symbol does shift + 2 normally create on your keyboard?

**Comment by Twisterking** [comment]
Hmm you are right: In Firefox `shift+2` **works** like it should. In Chrome and Safari (both up-to-date), `shift+2` does **not work**, while all the other numbers work.
On a german keyboard Shift+2 creates this apostrophe: `"`

**Comment by Twisterking** [comment]
Ok so just fyi: For some reason some combinations can't be bound like they should: `Shift+2` does not work in Chrome and Safari - this combo creates a `"`on a german keyboard. So actually also binding to `"` does the trick. May be a bug in Mousetrap I don't know but this little workaround works for me! :+1:
