### ISSUE TITLE
Started new canonical branch moustrap-js/mousetrap

### ISSUE THREAD

**Issue by robincafolla** [ccampbell/mousetrap#325]
After attempting to get in touch with @ccampbell before Christmas I've taken the drastic action of forking mousetrap to a new [repo](https://github.com/mousetrap-js/mousetrap).

My intention is that the new branch will take and merge pull requests and fix issues. I also hope to add maintainers from anyone interested (perhaps initially from anyone who has issued a pull request). I don't plan to add any new features for now.

If people post issues there I'll attempt to resolve them.

I don't intend to take over the project from @ccampbell. If he gets in touch and asks for admin access to the new repo, he'll be given it; I just want to see that some of the bugs get worked out.

**Comment by kafeltz** [comment]
I see @ccampbell has public activity. So, he's alive. Should we try to contact him somehow?

**Comment by robincafolla** [comment]
I tried emailing him before Christmas. You're welcome to try yourself.

I don't really like forking without his input, but the issues are starting to duplucate due to lack of fixes and as far as I can see he hasn't contributed in about 6 months. Better to keep the project ticking over and hand it back to him then let it die due to inactivity.

**Comment by ccampbell** [comment]
I'm sorry. I am alive. I am here. The main issue is just that I don't have a lot of time to devote to working on open source projects right now. I would not classify mousetrap or any of my other projects as dead. I just think the project and api are in a pretty stable state where they don't need constant attention so I haven't been actively developing it. 

I will definitely fix any huge glaring bugs, but as far as implementing new features/etc. you are more than welcome to add them in a fork of your own.

I will try to get through at least some of the issues and pull requests. Are there any specific things that are preventing you (or others) from using mousetrap right now that need to be addressed immediately?

**Comment by robincafolla** [comment]
Hi @ccampbell. I think there are a just a lot of small issues: missing key support and some sequence bugs. I've looked through the issues and a lot of the stuff seems duplicated.

Would you be willing to add some other people as maintainers? There were a few [here](https://github.com/ccampbell/mousetrap/issues/305) who were interested.
