### ISSUE TITLE
pause and unpause

### ISSUE THREAD

**Issue by bobabarbanel** [ccampbell/mousetrap#335]
I do not understand how to add the dowloadable pause/unpause extension that is documented in (https://craig.is/killing/mice) Mousetrap.
How does the code get inserted in the .js file?

Bob Abarbanel
bob.abarbanel@gmail.com

**Comment by michaelmathy** [comment]
Hello

Just download this file that you save in your project /Web site as
mousetrap-pause.min.js

https://raw.githubusercontent.com/ccampbell/mousetrap/master/plugins/pause/mousetrap-pause.min.js

And then in the page where you want to use it, just after the line where
you download mousetrap.js add a script tag to download it.

It should look like this:

<script src="mousetrap.js"></script>
<script src="mousetrap-pause.min.js"></script>

Le lun. 14 mars 2016 21:59, bobabarbanel <notifications@github.com> a
écrit :

**Comment by ccampbell** [comment]
Closing this since @michaelmathy provided instructions

**Comment by roelvan** [comment]
How would this work with `import`? This works: `import Mousetrap from 'mousetrap'`, but I cannot add the pause plugin for some reason.

**Comment by ChenMo91** [comment]
> How would this work with `import`? This works: `import Mousetrap from 'mousetrap'`, but I cannot add the pause plugin for some reason.

I have the same problem

**Comment by getninjaN** [comment]
Not sure if people are still having problem with `import` or not, but I had the same problem and got it working by doing this in a Vue application:
```javascript
const mousetrap = require("mousetrap")
require("mousetrap/plugins/pause/mousetrap-pause")

const vueMousetrap = {
  install: function (Vue) {
    Vue.prototype.$mousetrap = mousetrap
  }
}

export default vueMousetrap
```
