### ISSUE TITLE
Key combo entered into text input

### ISSUE THREAD

**Issue by andrewfleming** [ccampbell/mousetrap#337]
Using Mousetrap to trigger a click event on a link which in turn triggers a form to be inserted into the DOM. The first text input of the inserted form receives focus, but the key combo used is appended to the text input's content.

Any suggestions on how I could avoid this?

Currently using this code:

`		
Mousetrap.bind( 'q', function() {
	var listTable = document.querySelector('.wp-list-table');
	if ( listTable !== null ) {
		var $hoverEl = $( ":hover" );
		var $hoverElLast = $hoverEl.last();
		var $row = $hoverElLast.closest( 'tr' );
		var $quickEdit = $( '.inline a', $row);
		$($quickEdit).trigger('click');
	}
});
`

**Comment by ccampbell** [comment]
Can you provide a js fiddle or something to see what you mean? This sounds to me like you need to either use `keyup` for your mousetrap listener or `e.preventDefault()` to prevent the browser from inserting text into the new input.

**Comment by andrewfleming** [comment]
Yep, `e.preventDefault()` was what I needed. Thank you!
