### ISSUE TITLE
Wrapping Elements fails

### ISSUE THREAD

**Issue by newzen** [ccampbell/mousetrap#340]
Hello, trying 

https://jsfiddle.net/newzen/tbtnwspL/

no binding key events are displayed

What I'm doing wrong

Thanks in advance

**Comment by ccampbell** [comment]
Wrapping elements only works for elements that actually can receive key events (form inputs, content editable, etc). 

I don't know if there are any browsers that fire key events attached to specific elements, most of the time they fire on the document itself.

You can wrap a form though and then any key events inside a form field will bubble to that mousetrap instance.

Hope this helps

**Comment by ccampbell** [comment]
Going to close this since it is not actually a bug. Please comment and/or reopen if there is actually a bug.

**Comment by bZichett** [comment]
@newzen I actually got this working by setting a tabindex=0 (or some other number) on the 'mousetrapped' element.

@ccampbell Did you know this was possible? 

BTW, Great library, thanks a ton.
