### ISSUE TITLE
Support numlock and scrolllock

### ISSUE THREAD

**Issue by iongion** [ccampbell/mousetrap#341]
These keys are abused by knob and different usb controls that exist for pc, such as ShuttleXpress, they usually send a sequnce of key combinations that start with 144

`144` - Num Lock
`145` - Scroll Lock

I've checked in the source code and there is no way to modify the `_MAP` as it is a private variable, neither is `_characterFromEvent` function.

Can this be done without modifying/forking the library ?

**Comment by iongion** [comment]
Handled by PR #342

**Comment by ccampbell** [comment]
The pull request was merged so this is now possible!
