### ISSUE TITLE
Documentation error for mod helper

### ISSUE THREAD

**Issue by tythewebguy** [ccampbell/mousetrap#347]
The documentation under "Combination of keys" appears to be incorrect. It shows 'ctrl+s' and 'command+s' where it should be 'mod+s'.

<img width="683" alt="screen shot 2016-07-05 at 9 22 45 am" src="https://cloud.githubusercontent.com/assets/1933030/16591785/69089c3a-4292-11e6-8264-bff1e442e06b.png">

**Comment by ccampbell** [comment]
Oh wow. This is very bizarre. This shows up correctly for me:

![v3h1](https://cloud.githubusercontent.com/assets/259316/16592019/b158ad30-42ac-11e6-9f52-c7a05e80b653.png)

I just made a lot of updates to Rainbow (my syntax highlighting library) so I wonder if it is some sort of strange issue there. If you disable javascript on the page does it show up correctly?

**Comment by tythewebguy** [comment]
I just checked the page again and it's correct now. Weird. I also took a
look at my browser history to make sure I wasn't on some other website (I
tend to rely on Google too much), and confirmed that I was at
https://craig.is/killing/mice. So I guess it's no longer a problem.

BTW, great library! We're using it pretty heavily in an Ember project and
it's been working great.

**Comment by ccampbell** [comment]
Thank you! Glad to hear it.

So weird. So rainbow processes the syntax highlighting using a webworker and assigns it back to the proper div using a randomly generated identifier:

https://github.com/ccampbell/rainbow/blob/3374f1322bfa01885ce7d19a7c5021336af09513/src/rainbow.js#L162

So I suppose this is technically possible if somehow both of those blocks were assigned the same identifier, but I feel like that is *extremely* unlikely. Going to close this out for now then.
