### ISSUE TITLE
Combo events which include left or right arrow keys will fire even if only the arrow key is pressed

### ISSUE THREAD

**Issue by okaybenji** [ccampbell/mousetrap#363]
For instance, with the following code:

```
Mousetrap.bind('backspace+capslock+left', function(e, combo) {
	alert('You pressed: ' + combo);
}, 'keydown');
```

Pressing just the `left` arrow key will trigger the alert, even though the user should have to press it in combination with the `backspace` and `capslock` keys.

This is a problem, for instance, in a video game in which diagonal movement is allowed, as different behavior is required when a player presses, e.g., `left` alone versus `up+left`.

See https://jsfiddle.net/59cgxmw3/

**Comment by ccampbell** [comment]
Key combos only work with modifier keys. See #323

**Comment by okaybenji** [comment]
Sorry, looked through the issues but didn't realize these were related. Thanks for the quick response! Can you recommend a library which supports combos without modifier keys?

**Comment by okaybenji** [comment]
For anyone interested, I'm just using the solution found here:

http://stackoverflow.com/questions/10655202/detect-multiple-keys-on-single-keypress-event-in-jquery
