### ISSUE TITLE
Doesn't seem to work when input[text] has focus on Chrome/Linux

### ISSUE THREAD

**Issue by davidjamesstone** [ccampbell/mousetrap#366]
Using Chrome on Linux (Mint), the following code doesn't fire when a textbox has focus. It's fine otherwise.

```
Mousetrap.bind(['command+s', 'ctrl+s'], function () {
  console.log('Saving...')
  return false
})
```

Great library BTW.

**Comment by Elvynia** [comment]
Mousetrap doesn't natively handle bindings in input fields. You have to use the global-bind plugin and the bindGlobal(...) method !

**Comment by davidjamesstone** [comment]
Thanks Elvynia.

I can see that's perfectly well [documented](https://craig.is/killing/mice#extensions) now!

I'll try and be less trigger happy next time.

Many thanks

Dave
