### ISSUE TITLE
Support for variables?

### ISSUE THREAD

**Issue by thetomester13** [ccampbell/mousetrap#370]
Great plugin! 

The one thing I'm seeing now is I can't pass in a variable to the binding function. For example, if I wanted to do something like this:
`
var links = $(".links");
for (var i = 0; i < links.length; i++) {
  var url = $(links[i]).attr("href");
  Mousetrap.bind(i, function() {
    window.location = url;
  });
};
`
I get the following error:
`TypeError: a.replace is not a function`
Thoughts on this?

**Comment by Elvynia** [comment]
Hey,

You should have provided more information on the error, you would have had a quicker answer. I pasted your code in a jsfiddle to check why it wasn't working. The Mousetrap.bind() method expect a string as first argument. So you need to use `'' + i` to pass a string and not a number.

Check this code : https://jsfiddle.net/1njmo554/.

**Comment by thetomester13** [comment]
Yep, this is exactly what I'm looking for, thanks!
