### ISSUE TITLE
Allow binding shortcut keys with a scope

### ISSUE THREAD

**Issue by tych0** [ccampbell/mousetrap#4]
I'd be interested in using this, but I need some sort of "scoping", i.e. hotkeys would dispatch differently based on what element is highlighted.

**Comment by Charizard** [comment]
:+1: for this feature.

**Comment by ccampbell** [comment]
@Charizard I totally forgot about this ticket, but it should actually be possible to create an extension now that you can create multiple mousetrap instances (as of version 1.5). All you'd have to do is create a different mousetrap instance for the different scopes you want and then switch which instance is active.  Something like

```javascript
var headerMousetrap = new Mousetrap();
headerMousetrap.bind('/', _focusSearch);

var appMousetrap = new Mousetrap();
appMousetrap.bind('ctrl+s', _save);
```

Then you could use the [pause extension](https://github.com/ccampbell/mousetrap/tree/master/plugins/pause) to do something like

```javascript
// app is focused so deactivate header
headerMousetrap.pause();
appMousetrap.unpause();
```

Or vice versa.

Hopefully that's enough to get you started.

**Comment by Charizard** [comment]
Thanks for the quick reply @ccampbell !!! 

Would try this and get back.

**Comment by FezVrasta** [comment]
I'm interested in a solution, does someone has one ready to use?

**Comment by Akryum** [comment]
@ccampbell Could this put in the docs? :smile_cat:
