### ISSUE TITLE
GPL2 Compatible Licensing

### ISSUE THREAD

**Issue by pento** [ccampbell/mousetrap#421]
We're using Mousetrap in the [WordPress Gutenberg project](https://github.com/WordPress/gutenberg), which will be merged into WordPress core later this year.

WordPress is licensed under the GPL2, which unfortunately isn't compatible with the Apache2.0 license. Being such a large project, we have to be quite strict about the license of any modules we use. I know this has come up in the past (#169), but due to it's immense history and huge contributor base, changing WordPress' license isn't a viable option.

Given the circumstances, would it be possible for Mousetrap to be released under a dual license? No hard feelings if you'd prefer not to, but I figured I'd ask. 🙂

**Comment by ccampbell** [comment]
Hey. Sorry I totally missed this. I am happy to help. Honestly, I am not sure what is required to offer it via dual license. What license would be compatible?

**Comment by ccampbell** [comment]
Did a little more reading about this. If you haven’t already replaced Mousetrap, I am open to dual licensing as MIT as well as Apache 2.0

**Comment by ccampbell** [comment]
I was doing a little more reading and also found this: https://blog.gerv.net/2016/09/gplv2-combination-exception-for-the-apache-2-license/

Would something like that work for you? It seems a bit simpler to add a clause to the existing license, but I am no lawyer.

**Comment by pento** [comment]
That option also works for me. [SPDX even supports this exception](https://spdx.org/licenses/LLVM-exception.html), so the license field in your `package.json` would become `(Apache-2.0 WITH LLVM-exception)`, and `npm` won't complain about the license being invalid. 🙂

**Comment by pento** [comment]
Awesome, thanks @ccampbell!
