### ISSUE TITLE
Key combo works but doesn't

### ISSUE THREAD

**Issue by evanvin** [ccampbell/mousetrap#426]
I am using Mousetrap with React and I understand how Mousetrap works, and I don't think (?) it's something I'm doing wrong. The code below executes, and pressing 'z' and 'k' at the same time prints 'pressed' to the console, but after hitting the sequence once, I can trigger _doSomething_ by just hitting the 'k' key. Is anyone else getting this issue? Am I forgetting an option or something?

```
doSomething = e => {
   console.log("pressed");
}

componentDidMount() {
   Mousetrap.bind("z+k", this.doSomething);
}

componentWillUnmount() {
   Mousetrap.unbind("z+k", this.doSomething);
}
```

**Comment by ccampbell** [comment]
Mousetrap only works for single keys and combinations that include modified keys (control, alt, shift, command). See #101.
