### ISSUE TITLE
Can we have trigger() able to trigger the default behavior of keys?

### ISSUE THREAD

**Issue by ttback** [ccampbell/mousetrap#43]
Nice api for the most part and I have been having fun with it to make my app much more usable than before with shortcuts. But one of the features require me to trigger default space-bar behavior at runtime. I am still trying the jquery event way at the moment. I wonder if there's plan to make trigger() actually triggering the default behavior if not mapped in mousetrap. Thanks.

**Comment by ccampbell** [comment]
I think this is outside of the scope of mousetrap. I don’t think it will be easy to come up with a cross browser solution that is simple. The [key-event.js](https://github.com/ccampbell/mousetrap/blob/b411d71ba244f552e5487a69e3129f4a60e39017/tests/libs/key-event.js) library included with the tests actually aims to do something like this so perhaps it could be repurposed to achieve this.

In any case, I am going to close this out
