### ISSUE TITLE
List of shortcuts is too long

### ISSUE THREAD

**Issue by mikeveltman** [ccampbell/mousetrap#439]
When I have more than a certain amount of shortcuts, the cheatsheet shortcutlist goes on under the page. It would be nice to have a scrollbar or have the list go on in multiple columns.

**Comment by jvosloo** [comment]
Umm... is this a joke? overflow: auto? If you don't know hat that means, then I take the snark right back.

**Comment by mikeveltman** [comment]
It wasn't a joke, I asked the question when I barely had any programming experience. Managed to solve it and forgot close the issue. Thanks for reminding me anyway

**Comment by jvosloo** [comment]
My apologies Mike - that was a little shitty of me. Not my best moment 😔

**Comment by mikeveltman** [comment]
No worries, now I look back at it it was indeed a 'stupid' question

**Comment by thanhtacles** [comment]
Where did you even find the list of all valid possible values of names of keys? I cannot for the life of me figure out how to input right control. rctrl r-ctrl right-ctrl right_ctrl ControlRight, none of them work

**Comment by mikeveltman** [comment]
@thanhtacles On the [documentation page](https://craig.is/killing/mice) of Mousetrap you can find the available shortcuts:

> ### Supported Keys
> For modifier keys you can use **shift**, **ctrl**, **alt**, or **meta**.
> You can substitute option for **alt** and **command** for **meta**.
> 
> Other special keys are **backspace**, **tab**, **enter**, **return**, **capslock**, **esc,** **escape**, **space**, **pageup**, **pagedown**, **end**, **home**, **left**, **up**, **right**, **down**, **ins**, **del**, and **plus**.
> 
> Any other key you should be able to reference by name like **a**, **/,** **$**, *, or =.

I can't find **right-ctrl** in that list so I suppose **right-ctrl** acts as normal **ctrl**.
Also in keyCode left and right ctrl buttons both have 17 as code. So there's no distinction being made between the keys.
