### ISSUE TITLE
Using "mousetrap" for class in inputs does not prevent mousetrap event from firing

### ISSUE THREAD

**Issue by phun-ky** [ccampbell/mousetrap#450]
with this code:

```html
<input type="search" class="mousetrap"/>
```

```javascript
Mousetrap.bind(['up','j'], function(e) {...}
```

Pressing `j` inside the input will fire event, even though it shouldn't..

**Comment by raquo** [comment]
It' is by design:

> By default all keyboard events will not fire if you are inside of a textarea, input, or select to prevent undesirable things from happening.

> If you want them to fire you can add the class `mousetrap` to the element.

https://craig.is/killing/mice

**Comment by phun-ky** [comment]
Yeah, doh. Didn't quite remember that. I wanted the user to traverse in search result with both `up/down` and `j/k`, but that obviously do not work :)
