### ISSUE TITLE
bindGlobal is not a function

### ISSUE THREAD

**Issue by TurbulentCupcake** [ccampbell/mousetrap#457]
I installed Mousetrap through npm and used it in my react code as follows:
`import * as Mousetrap from 'mousetrap';`
.
.
.
` componentDidMount () {
      Mousetrap.bindGlobal('enter', this.submitSearch);
`
However, this returns the following issue:
`Uncaught TypeError: mousetrap__WEBPACK_IMPORTED_MODULE_13__.bindGlobal is not a function`

Is there a way around this?

**Comment by haykam821** [comment]
You need to use [`mousetrap-global-bind`](https://www.npmjs.com/package/mousetrap-global-bind) since it is a plugin.

**Comment by browner12** [comment]
Since the `bindGlobal` code is included in the normal NPM download, shouldn't there be a way to do it without going to the other NPM package?

**Comment by dinhtungdu** [comment]
@browner12 You can import it, like this:
`import 'mousetrap/plugins/global-bind/mousetrap-global-bind';`

**Comment by adil62** [comment]
@TurbulentCupcake Please close this issue as completed.
