### ISSUE TITLE
documentation: unbind needs action

### ISSUE THREAD

**Issue by forresto** [ccampbell/mousetrap#55]
On http://craig.is/killing/mice "II. Mousetrap.unbind" should mention that you need to pass the action, like:

```
Mousetrap.unbind('?', 'keydown');
```

**Comment by Elvynia** [comment]
Thanks, it helped me !

**Comment by gnihi** [comment]
...and the unbind works like a charm. That was a helpful information, thanks!
This should definitely be added to the documentation.

**Comment by ccampbell** [comment]
Just added this. Thanks!
