### ISSUE TITLE
Function Keys [F1-F12]

### ISSUE THREAD

**Issue by buschtoens** [ccampbell/mousetrap#83]
Is it possible to reliably support the function keys F1-F12?

**Comment by SwiTool** [comment]
Hmh.

```javascript
Mousetrap.bind(['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12'], (e, key) => {
  console.log(key);
});
```
when I hit F1, F2, etc until F12, it displays : 
```
f1
f2
f3
f5
f6
f7
f8
f9
f10
f11
f12
```
f4 is missing. Do you have the same problem ?

I use F keys with the macbook pro touchbar.

Thanks

**Comment by mix3d** [comment]
@SwiTool This is a very late response, but I found on my mac I had to unbind a system keybind for f11 in order to get f11 to work, so that may be something to look into.

**Comment by SwiTool** [comment]
@mix3d Woops, fell asleep for the last 2 years. 😄 
Yeah that's probably it. But it seems a bit awkward to be constrained to unbind system keys to use a program. I guess you should not bind the special function keys. That's all ^^
